<a href="https://colab.research.google.com/github/nasif-raihan/Ml-and-DL-Codes/blob/main/NumPy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**BASIC**

In [ ]:
#Multiplication
a = np.array([1,2,3])
b = np.array([2,3,4])

a*b 

array([ 2,  6, 12])

In [ ]:
#Dimension
a = np.array([[[1,2], [2,3], [3,4]]])
a.ndim

3

In [ ]:
#Shape
a.shape

(1, 3, 2)

In [ ]:
#Type

a.dtype

dtype('int64')

In [ ]:
#Size
print(a.itemsize, end=" ")
a = np.array([[2,3], [3,4]],dtype='int16')
a.itemsize

2 

2

In [ ]:
#Total size

a.nbytes

8

**Accessing/Changing specific elements, rows, columns etc**

In [ ]:
a = np.array([[1,2,3,4], [7,6,5,4]])
print(a)

[[1 2 3 4]
 [7 6 5 4]]


In [ ]:
#Get specific element

a[1,-3]

6

In [ ]:
#get specific row

a[0, :]

array([1, 2, 3, 4])

In [ ]:
#get specific column

a[:, 0]

array([1, 7])

In [ ]:
a[0, 1:3]

array([2, 3])

In [ ]:
#replacing
a[:, 1] = [9, 9]

a

array([[1, 9, 3, 4],
       [7, 9, 5, 4]])

**Initializing Different types of Arrays**

In [ ]:
#Zero

a = np.zeros((2,3))

a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#One

b = np.ones((4, 2, 2), dtype='int32')

b

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#any other value

c = np.full((2,2), 'f')

c

array([['f', 'f'],
       ['f', 'f']], dtype='<U1')

In [ ]:
#Random decimal value

r = np.random.rand(4, 2)  #no tuple

r

array([[0.6309592 , 0.77186933],
       [0.99719744, 0.85545358],
       [0.43839121, 0.93473168],
       [0.05833995, 0.3583787 ]])

In [ ]:
#Random Integer value

r = np.random.randint(4, size= (3, 3))

print(r)

r = np.random.randint(3,5, size=(3,4))  #5 exclusive here

print("\nFrom 3 to 4 values ony: \n", r)

[[3 3 1]
 [1 1 2]
 [3 2 0]]

From 3 to 4 values ony: 
 [[3 4 4 4]
 [4 4 4 3]
 [4 3 3 4]]


In [ ]:
#Identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Repeat an Array

arr = np.array([1,2,3])
r1 = np.repeat(arr, 3) #axis = 0

print(r1)

arr = np.array([[1, 2, 3]])
r2 = np.repeat(arr, 3, axis = 0)
r3 = np.repeat(arr, 3, axis = 1)

print("\n", r2)
print("\n", r3)

[1 1 1 2 2 2 3 3 3]

 [[1 2 3]
 [1 2 3]
 [1 2 3]]

 [[1 1 1 2 2 2 3 3 3]]


**Build this array:** 
       [[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]] 

In [ ]:
o = np.ones((5,5))
z = np.zeros((3,3))

#print(o, "\n\n", z, "\n")

z[1, 1] = 9

output = o

output[1:4, 1:4] = z

output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**Be careful while copying Arrays**

In [ ]:
a = np.array([1, 2, 3])

b = a.copy()

b[0] = 10

print(b, "\n", a)

[10  2  3] 
 [1 2 3]


**Mathematics**

In [ ]:
print(a)
print(a + 2)
print(a - 4)
print(a * 2)
print(a / 2)
print(a ** 2)
print(np.cos(a))
print(a + b)

[1 2 3]
[3 4 5]
[-3 -2 -1]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]
[ 0.54030231 -0.41614684 -0.9899925 ]
[11  4  6]


**Linear Algebra**

In [ ]:
#matrix multiplication

a = np.full((2,2), 3)
print(a, "\n\n")
b = np.full((2, 1), 4)
print(b, "\n\n")
np.matmul(a, b)

[[3 3]
 [3 3]] 


[[4]
 [4]] 




array([[24],
       [24]])

In [ ]:
#Determinant

c = np.identity(3)
np.linalg.det(c)

1.0

**Stistics**

In [ ]:
stat = np.array([[1,2,3], [8,6,4]])

print(np.min(stat))
print(np.max(stat))
print(np.min(stat, axis = 1))
print(np.max(stat, axis = 1))
print(np.sum(stat))
print(np.sum(stat, axis = 0))   #column wise sum
print(np.sum(stat, axis = 1))   #row wise sum

1
8
[1 4]
[3 8]
24
[9 8 7]
[ 6 18]


**Reorganizing Array**

In [ ]:
print(stat.reshape(6,1), "\n")
print(stat.reshape(1, 6))

[[1]
 [2]
 [3]
 [8]
 [6]
 [4]] 

[[1 2 3 8 6 4]]


In [ ]:
#vertically stacking vectors

v1 = np.array([1, 2, 3, 4])
v2 = np.array([2, 4, 6, 8])

np.vstack([v1, v2, v1, v2])   #All similar kind of matrix

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [1, 2, 3, 4],
       [2, 4, 6, 8]])

In [ ]:
#Horizontal stack

np.hstack([v1, v2])

array([1, 2, 3, 4, 2, 4, 6, 8])

**Miscellaneous**